#!/bin/bash
set -o errexit -o pipefail

gimme \
	my/dotfiles \
	my/difftool \
	my/mergetool \
	liquidprompt \
	git-extras \
	tmux \
	tree \
	vim \
	my/www \
	my/js \
	my/py \
	my/db \
	my/go \
	my/sh \
	atom
