#!/bin/bash
set -o errexit -o pipefail

gimme \
	kylepdavis/dotfiles \
    tools/db \
    tools/difftool \
    tools/git \
    tools/go \
    tools/js \
    tools/mergetool \
    tools/py \
    tools/rust \
    tools/sh \
    tools/text \
    tools/www \
	tmux \
	tree \
	pstree \
    --
