#!/bin/bash
set -o errexit -o pipefail

gimme pip

PKG=${0##*/}
if ! has "$PKG" && ! python -c "import $PKG" &>/dev/null; then
	if [[ "$OS" = "Darwin" ]]; then
		mkdir -p "$PYTHONPATH"
		pip install --install-option="--prefix=$(brew --prefix)" "$PKG"
		! [ -f "$PYTHONPATH/$PKG" ]  ||  ln -sfv "$PYTHONPATH/$PKG" "$(brew --prefix)/bin/$PKG"
	else
		if ! gimme_pkg "$PKG"; then
			echo "# WARN: Unable to get system package \"$PKG\", trying pip/easy_install instead ..."
			sudo pip install "$PKG"
		fi
	fi
fi
