#!/bin/bash
set -o errexit -o pipefail

PKG=${0##*/}
if ! has "$PKG" && ! python -c "import $PKG" &>/dev/null; then
	gimme pip
	if [[ "$OS" = "Darwin" ]]; then
		pip install --user "$PKG"
	else
		if ! gimme_pkg "$PKG"; then
			echo "# WARN: Unable to get system package \"$PKG\", trying pip/easy_install instead ..."
			pip install --user "$PKG"
		fi
	fi
fi
