#!/bin/bash
set -o errexit -o pipefail

gimme java

if [[ "$OS" = "Darwin" ]]; then
	gimme_pkg android-studio
else
	if ! has android-studio; then
		URL='https://dl.google.com/dl/android/studio/ide-zips/2.0.0.20/android-studio-ide-143.2739321-linux.zip'
		TMP_FILE="/tmp/gimme.android-studio.2.0.0.zip"
		curl -fSLC- "$URL" -o "$TMP_FILE"
		cd "$HOME"
		unzip "$TMP_FILE"
		rm "$TMP_FILE"
		ln -sfv "$HOME/android-studio/bin/studio.sh" "$HOME/bin/android-studio"
	fi
fi
