#!/bin/bash
set -o errexit -o pipefail
if [[ "$OS" = "Darwin" ]]; then
	[[ -d "$HOME/Applications/Atom.app/" ]]  ||  brew cask install atom
	defaults write com.github.atom ApplePressAndHoldEnabled -bool false
else
	if ! has atom; then
		URL='https://atom.io/download/deb'
		TMP_FILE="/tmp/atom.latest.deb"
		curl -fsSLC- "$URL" -o "$TMP_FILE"
		sudo dpkg -i "$TMP_FILE"
		rm "$TMP_FILE"
	fi
fi
