#!/bin/bash
set -o errexit -o pipefail
if ! has tlmgr; then
	if [[ "$OS" = "Darwin" ]]; then
		gimme_pkg basictex
		export PATH="$PATH:/Library/TeX/texbin"
		sudo tlmgr update --self
		sudo tlmgr install titling framed
	else
		echo "TODO: add BasicTex for Linux!"
	fi
fi
