#!/bin/bash
set -o errexit -o pipefail

has git  ||  gimme_pkg git

[[ "$(git config --global --get core.pager)" ]]  ||  git config --global core.pager 'less --raw-control-chars'

[[ "$(git config --global --get color.ui)" ]]  ||  git config --global color.ui true

if ! git --version | grep -q 'git version 1'; then
	[[ "$(git config --global --get push.default)" ]]  ||  git config --global push.default simple
fi

if ! [[ "$(git config --global --get credential.helper)" ]]; then
	if [[ "$OS" = "Darwin" ]]; then
		git config --global credential.helper "osxkeychain"
	else
		git config --global credential.helper "cache --timeout=3600"
	fi
fi
