#!/bin/bash
has git  ||  gimme_pkg git
if ! [[ -f "$HOME/.gitconfig" ]]; then
	git config --global color.ui true
	if [[ "$OS" = "Darwin" ]]; then
		git config --global credential.helper "osxkeychain"
	else
		git config --global credential.helper "cache --timeout=3600"
	fi
fi

