#!/bin/bash
set -o errexit -o pipefail

gimme git

has git-alias  ||  gimme_pkg git-extras

if ! [[ "$(git alias --global)" ]]; then
    echo "#INFO: Configuring git alias entries..."
    git alias --global br branch
    git alias --global ci commit
    git alias --global co checkout
    git alias --global di diff
    git alias --global st status
    git alias --global sw switch
    git alias --global pi cherry-pick

    git alias --global | sed 's/^/#    /'
fi
