#!/bin/bash
set -o errexit -o pipefail
if [[ "$OS" = "Darwin" ]]; then
	brew cask install google-chrome
else
	if ! has google-chrome && ! has chromium-browser; then
		gimme_pkg chromium-browser
	fi
fi
