#!/bin/bash
set -o errexit -o pipefail

if [[ "$OS" = "Darwin" ]]; then
	[ -d "/Library/PreferencePanes/JavaControlPanel.prefPane" ]  ||  brew cask install java
else
	has java  ||  gimme_pkg openjdk-8-jdk
fi
