#!/bin/bash
set -o errexit -o pipefail

REPO_URL="https://github.com/nojhan/liquidprompt"
REPO_DIR="$HOME/.liquidprompt"

if ! [[ -d "$REPO_DIR" ]]; then

	gimme git

	git clone "$REPO_URL" "$REPO_DIR"

else

	cd "$REPO_DIR"
	git pull

fi
