#!/bin/bash
set -o errexit -o pipefail

gimme python

if ! has pip; then
	if [[ "$OS" = "Darwin" ]]; then
		curl -fsSL "https://bootstrap.pypa.io/get-pip.py" | python - --user
	else
		gimme_pkg python-pip || sudo easy_install pip
	fi
fi
