#!/bin/bash
set -o errexit -o pipefail

gimme python

if ! has pip; then
	if [[ "$OS" = "Darwin" ]]; then
		mkdir -p "$PYTHONPATH"
		easy_install -d "$PYTHONPATH" "pip"
		ln -sfv "$PYTHONPATH/pip" "$(brew --prefix)/bin/pip"
	else
		sudo easy_install pip
	fi
fi
